### ISSUE TITLE
fix conflicting handlers

### ISSUE THREAD

**Issue by SpEcHiDe** [SpEcHiDe/MyTelegramOrgRoBot#13]
1474051277 != 'CQADBAADggcAAhPBQFAtETYJlEFcHQI'

**Comment by abosadalfrahi** [comment]
1474051277

**Comment by abosadalfrahi** [comment]
CQADBAADggcAAhPBQFAtETYJlEFcHQI

**Comment by abosadalfrahi** [comment]
+48699513332

**Comment by mbeiranvand** [comment]
[microsoft](https://www.microsoft.com) 
#9

**Comment by mbeiranvand** [comment]
my telegram robot disable,and telegram need emplody personal the control,setting,and other,robot telegram anti people is

**Comment by mbeiranvand** [comment]
google is for me and me louk this company
