### ISSUE TITLE
My Bot Isn't Starting Up

### ISSUE THREAD

**Issue by Demonflowne** [SpEcHiDe/MyTelegramOrgRoBot#2]
I get this error whenever i deploy bot to heroku log page causing it not to start.

![Screenshot_20200511_141408](https://user-images.githubusercontent.com/64446667/81565713-b8e86380-9391-11ea-96d3-2f497f682d37.jpg)

**Comment by SpEcHiDe** [comment]
wrong _ENVIRONMENT_ variable. please set correct value for **URL** field.
